Update BrutalKAT.py
Anish-M-code/Brutal-KAT-Keyword-search-tool pull request #1
Opened 2020-08-20 10:07 UTC by gowtham758550

Added function to find total no of words, letters and lines

2020-08-20 11:06 UTC, Anish-M-code requested changes
in line 52 content=f.read() is very risky python with load contents of large file directly into memory . consider situation where you have 2 gb ram but processing 8 gb file , the system may hang or crash.

i would like to see a function which returns number of characters, number of words , number of lines without causing memory issues as we deal with large files.

Anyway Thanks a lot for your great work and spending Time to improve this project :).

Please solve that memory issue then the patch will be merged for sure!

2020-08-20 12:30 UTC, Anish-M-code requested changes
i think it would be better to debug to add the word count , line count and character count in different function. i will merge the code anyway but it will reduce a few lines. waiting for your response...

2020-08-29 09:34 UTC, gowtham758550 commented
I added only line count try to review.

2020-08-29 11:34 UTC, Anish-M-code approved these changes

2020-08-29 11:34 UTC, merged